### ISSUE TITLE
Works with no vaild file path

### ISSUE THREAD

**Issue by Add00** [cduarte3/f2read#7]
Generates good responses with files, however AI still generates a response even when no valid files are provided.

**Comment by cduarte3** [comment]
CLI tool now exits the program if a file has not been found instead of still generating the README.md with empty or garbage content. 

If any errors are found reading, locating, writing, etc. with the file specified, the program will display an error log and exit.

Was completed in commit: db3309cb9d25d2b87e58ac32f1c6786bdaa8a2e3
